config/routes.rb
Rails.application.routes.draw do
  get    'signup',  to: 'users#new'
  get    'login',   to: 'sessions#new'
  delete 'logout',  to: 'sessions#destroy'
  get    'welcome', to: 'pages#welcome'

  resources :users,    only: [:create]
  resources :sessions, only: [:create]
  resources :tasks
  
  root 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user 
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy


  validates_presence_of :username, :email, unless: :guest?
  validates_uniqueness_of :username, allow_blank: true
  validates_confirmation_of :password

  has_secure_password validations: false

  def self.new_guest
    new { |u| u.guest = true }
  end

  def name
    guest ? "Guest" : username
  end

  def move_to(user)
    tasks.update_all(user_id: user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome 
    #code
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout 'users'

  def new
  end

  def create
    user = User.find_by_username(params[:user][:username])
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'login successfully!'
    else
      flash.now.alert = "Name or password is invalid"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, alert: 'Logout successfully!'
  end

  private

    def user_params
      #code
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    if current_user
      @incomplete_tasks = current_user.tasks.where(complete: false)
      @complete_tasks   = current_user.tasks.where(complete: true)
    else
      @incomplete_tasks = []
      @complete_tasks   = []
    end
  end

  def create
    @task = current_user.tasks.create!(task_params)

    respond_to do |format|
      format.html { redirect_to tasks_path }
      format.js
    end
  end

  def update
    @task = current_user.tasks.find(params[:id])
    @task.update_attributes!(task_params)

    respond_to do |format|
      format.html { redirect_to tasks_path }
      format.js
    end
  end

  def destroy
    @task = current_user.tasks.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_path }
      format.js
    end
  end

  private

    def task_params
      params.require(:task).permit(:name, :complete)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = params[:user] ? User.new(user_params) : User.new_guest
    if @user.save
      current_user.move_to(@user) if current_user && current_user.guest?
      session[:user_id] = @user.id
      flash[notice] = "Sign up successfully!" unless current_user.guest?
      redirect_to root_path
    else
      render :new
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { notice: 'success', alert: 'danger' }.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch(key.to_sym, key)
  end

  def user_facing_flashes
    flash.to_hash.slice('alert', 'notice', 'warning', 'info')
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Checklist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-info">
    <div class="container">
      <%= render 'shared/nav' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Checklist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-info">
    <div class="container">
      <%= render 'shared/nav' %>
      <%= render 'shared/flashes' %>
      <%= yield %>
      <div class="bg-light p-3 mt-5">
        <%= debug(params) if Rails.env.development? %>
      </div>
    </div>
  </body>
</html>

app/views/pages/welcome.html.erb
<h1>pages#welcome</h1>

app/views/shared/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-<%= flash_class(key) %> alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/shared/_nav.html.erb
<ul class="nav justify-content-end bg-light">
  <li class="nav-item">
    <%= link_to 'tasks', tasks_path, class: 'nav-link' %>
  </li>
  <% if current_user %>
    <div class="dropdown">
      <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= current_user.name %>
      </button>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
        <% if current_user.guest? %>
          <%= link_to 'Become a member', signup_path, class: 'dropdown-item' %>
        <% else %>
          <%= link_to 'logout', logout_path, method: :delete, class: 'dropdown-item' %>
        <% end %>
      </div>
    </div>
  <% else %>
    <li class="nav-item">
      <%= link_to 'signup', signup_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'login', login_path, class: 'nav-link' %>
    </li>
  <% end %>
</ul>

app/views/tasks/_form.html.erb
<%= simple_form_for Task.new, wrapper: :inline_form, html: { class: 'form-inline my-3' }, 
  data: { remote: true }, authenticity_token: true  do |f| %>
  <%= f.input :name, placeholder: 'task name', input_html: { class: 'mr-2' } %>
  <%= f.submit "Add Task", class: 'btn btn-primary' %>
<% end %>

app/views/tasks/_task.html.erb
<%= simple_form_for task, remote: true, :authenticity_token => true do |f| %>
  <%= f.input_field :complete, inline_label: task.name %>
  <%= link_to "(remove)", task, method: :delete, data: {confirm: "Are you sure?"}, remote: true %>
<% end %>

app/views/tasks/create.js.erb
$('#no-tasks').addClass('d-none');

<% if @task.complete? %>
  $('#js-complete-tasks').append('<%= j render @task %>');
<% else %>
  $('#js-incomplete-tasks').append('<%= j render @task %>');
<% end %>

$('#edit_task_<%= @task.id %>').find('input[type=checkbox]').click(function() {
  $(this).parent('label').parent('form').submit();
  console.log(this);
});

$('#new_task #task_name').val('');

app/views/tasks/destroy.js.erb
$('#edit_task_<%= @task.id %>').remove();

<% if current_user.tasks.all.count == 0 %>
  $('#no-tasks').removeClass('d-none');
<% end %>

app/views/tasks/index.html.erb
<% if current_user.nil? %>
  <div class="jumbotron my-3">
    <h1 class="display-3">Awesome To-Do List</h1>
    <p class="lead">
      Welcome to the ultimate Awesome To-Do List application! Because all you need to organize your life is another to-do app. This one isn't like the others though, oh no! It is completely unique and will change everything.
    </p>
    <p class="lead">
      <%= button_to "Try it for free!", users_path, class: "btn btn-primary btn-lg" %>
    </p>
    <p>Already signed up? <%= link_to "Log in", login_path %></p>
  </div>
<% else %>

  <%= render 'form' %>

  <% if @incomplete_tasks.empty? && @complete_tasks.empty? %>
    <p id="no-tasks">Currently no tasks. Add one above.</p>
  <% end %>

    <div class="card bg-dark text-white my-3">
      <div class="card-header h2">Incomplete Tasks</div>
      <div class="card-body">
        <div class="card-text incomplete-tasks" id="js-incomplete-tasks">
          <%= render @incomplete_tasks %>
        </div>
      </div>
    </div>
    <div class="card bg-light my-3">
      <div class="card-header h2">Complete Tasks</div>
      <div class="card-body">
        <div class="card-text complete-tasks" id="js-complete-tasks">
          <%= render @complete_tasks %>
        </div>
      </div>
    </div>

<% end %>

app/views/tasks/update.js.erb
<% if @task.complete? %>
  $('#edit_task_<%= @task.id %>').appendTo('#js-complete-tasks');
<% else %>
  $('#edit_task_<%= @task.id %>').appendTo('#js-incomplete-tasks');
<% end %>

app/views/users/new.html.erb
<div class="row justify-content-center">
  <div class="col-md-6">
    <div class="card border-primary bg-light mt-5">
      <div class="card-body">
        <h1 class="text-center">Sign up</h1>
        <%= simple_form_for @user do |f| %>
          <%= f.input :username %>
          <%= f.input :email %>
          <%= f.input :password %>
          <%= f.input :password_confirmation %>
          <%= f.submit 'Sign up', class: 'btn btn-primary btn-block btn-lg' %>
        <% end %>
        <p>Already signed up? <%= link_to "Log in", login_path %></p>
      </div>
    </div>
  </div>
</div>